// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoply_Data_Access;

#nullable disable

namespace Shoply_Data_Access.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250803205611_SeedProductDataUpdate")]
    partial class SeedProductDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shoply_Server_Side.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "men's clothing",
                            Description = "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
                            Image = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Price = 109.95,
                            Title = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Category = "men's clothing",
                            Description = "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
                            Image = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
                            Price = 22.300000000000001,
                            Title = "Mens Casual Premium Slim Fit T-Shirts "
                        },
                        new
                        {
                            Id = 3,
                            Category = "men's clothing",
                            Description = "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm-hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
                            Image = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            Price = 55.990000000000002,
                            Title = "Mens Cotton Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Category = "men's clothing",
                            Description = "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
                            Image = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            Price = 15.99,
                            Title = "Mens Casual Slim Fit"
                        },
                        new
                        {
                            Id = 5,
                            Category = "jewelery",
                            Description = "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
                            Image = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
                            Price = 695.0,
                            Title = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet"
                        },
                        new
                        {
                            Id = 6,
                            Category = "jewelery",
                            Description = "Satisfaction Guaranteed. Return or exchange any order within 30 days. Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed.",
                            Image = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
                            Price = 168.0,
                            Title = "Solid Gold Petite Micropave "
                        },
                        new
                        {
                            Id = 7,
                            Category = "jewelery",
                            Description = "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
                            Image = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
                            Price = 9.9900000000000002,
                            Title = "White Gold Plated Princess"
                        },
                        new
                        {
                            Id = 8,
                            Category = "jewelery",
                            Description = "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
                            Image = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
                            Price = 10.99,
                            Title = "Pierced Owl Rose Gold Plated Stainless Steel Double"
                        },
                        new
                        {
                            Id = 9,
                            Category = "electronics",
                            Description = "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatible with Windows 7, 8, 10; May require reformatting for other operating systems",
                            Image = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
                            Price = 64.0,
                            Title = "WD 2TB Elements Portable External Hard Drive - USB 3.0 "
                        },
                        new
                        {
                            Id = 10,
                            Category = "electronics",
                            Description = "Easy upgrade for faster boot up, shutdown, application load and response. Boosts burst write performance, making it ideal for typical PC workloads.",
                            Image = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
                            Price = 109.0,
                            Title = "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s"
                        },
                        new
                        {
                            Id = 11,
                            Category = "electronics",
                            Description = "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. High efficiency performance - low power consumption. Support for TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
                            Image = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
                            Price = 109.0,
                            Title = "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III"
                        },
                        new
                        {
                            Id = 12,
                            Category = "electronics",
                            Description = "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
                            Image = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
                            Price = 114.0,
                            Title = "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive"
                        },
                        new
                        {
                            Id = 13,
                            Category = "electronics",
                            Description = "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount. Refresh Rate: 75Hz - Using HDMI port",
                            Image = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
                            Price = 599.0,
                            Title = "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin"
                        },
                        new
                        {
                            Id = 14,
                            Category = "electronics",
                            Description = "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side. Quantum dot (QLED) technology, HDR support and factory calibration provide stunningly realistic and accurate color and contrast. Advanced gaming features include fast 144Hz refresh rate and 1ms motion blur reduction (MPRT) for incredibly smooth motion scenes.",
                            Image = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
                            Price = 999.99000000000001,
                            Title = "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor"
                        },
                        new
                        {
                            Id = 15,
                            Category = "women's clothing",
                            Description = "Note: The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece.",
                            Image = "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
                            Price = 56.990000000000002,
                            Title = "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats"
                        },
                        new
                        {
                            Id = 16,
                            Category = "women's clothing",
                            Description = "100% POLYURETHANE (shell) 100% POLYESTER (lining) 75% POLYESTER 25% COTTON (sweater), Faux leather material for style and comfort / 2 pockets of front, detail stitching at sides",
                            Image = "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
                            Price = 29.949999999999999,
                            Title = "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket"
                        },
                        new
                        {
                            Id = 17,
                            Category = "women's clothing",
                            Description = "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design.",
                            Image = "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
                            Price = 39.990000000000002,
                            Title = "Rain Jacket Women Windbreaker Striped Climbing Raincoats"
                        },
                        new
                        {
                            Id = 18,
                            Category = "women's clothing",
                            Description = "95% RAYON 5% SPANDEX",
                            Image = "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
                            Price = 9.8499999999999996,
                            Title = "MBJ Women's Solid Short Sleeve Boat Neck V"
                        },
                        new
                        {
                            Id = 19,
                            Category = "women's clothing",
                            Description = "100% Polyester Moisture Transport System sweeps away sweat and dries quickly",
                            Image = "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
                            Price = 7.9500000000000002,
                            Title = "Opna Women's Short Sleeve Moisture"
                        },
                        new
                        {
                            Id = 20,
                            Category = "women's clothing",
                            Description = "95%Cotton,5%Spandex",
                            Image = "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
                            Price = 12.99,
                            Title = "DANVOUY Womens T Shirt Casual Cotton Short"
                        });
                });

            modelBuilder.Entity("Shoply_Server_Side.Models.Product", b =>
                {
                    b.OwnsOne("Shoply_Server_Side.Models.Rating", "Rating", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<double>("Rate")
                                .HasColumnType("float");

                            b1.HasKey("ProductId");

                            b1.ToTable("Product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1,
                                    Count = 120,
                                    Rate = 3.8999999999999999
                                },
                                new
                                {
                                    ProductId = 2,
                                    Count = 259,
                                    Rate = 4.0999999999999996
                                },
                                new
                                {
                                    ProductId = 3,
                                    Count = 500,
                                    Rate = 4.7000000000000002
                                },
                                new
                                {
                                    ProductId = 4,
                                    Count = 430,
                                    Rate = 2.1000000000000001
                                },
                                new
                                {
                                    ProductId = 5,
                                    Count = 400,
                                    Rate = 4.5999999999999996
                                },
                                new
                                {
                                    ProductId = 6,
                                    Count = 70,
                                    Rate = 3.8999999999999999
                                },
                                new
                                {
                                    ProductId = 7,
                                    Count = 400,
                                    Rate = 3.0
                                },
                                new
                                {
                                    ProductId = 8,
                                    Count = 100,
                                    Rate = 1.8999999999999999
                                },
                                new
                                {
                                    ProductId = 9,
                                    Count = 203,
                                    Rate = 3.2999999999999998
                                },
                                new
                                {
                                    ProductId = 10,
                                    Count = 470,
                                    Rate = 2.8999999999999999
                                },
                                new
                                {
                                    ProductId = 11,
                                    Count = 319,
                                    Rate = 4.7999999999999998
                                },
                                new
                                {
                                    ProductId = 12,
                                    Count = 400,
                                    Rate = 4.7999999999999998
                                },
                                new
                                {
                                    ProductId = 13,
                                    Count = 250,
                                    Rate = 2.8999999999999999
                                },
                                new
                                {
                                    ProductId = 14,
                                    Count = 140,
                                    Rate = 2.2000000000000002
                                },
                                new
                                {
                                    ProductId = 15,
                                    Count = 235,
                                    Rate = 2.6000000000000001
                                },
                                new
                                {
                                    ProductId = 16,
                                    Count = 340,
                                    Rate = 2.8999999999999999
                                },
                                new
                                {
                                    ProductId = 17,
                                    Count = 679,
                                    Rate = 3.7999999999999998
                                },
                                new
                                {
                                    ProductId = 18,
                                    Count = 130,
                                    Rate = 4.7000000000000002
                                },
                                new
                                {
                                    ProductId = 19,
                                    Count = 146,
                                    Rate = 4.5
                                },
                                new
                                {
                                    ProductId = 20,
                                    Count = 145,
                                    Rate = 3.6000000000000001
                                });
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
